name: NetherGate
main: com.elmakers.mine.bukkit.plugins.nether.NetherGatePlugin
version: 0.41
website: http://mine.elmakers.com
author: NathanWolf
description : An attempt to reproduce Nether Gates in SMP
commands:
  nether:
    description: Administer Nether areas
    usage: Use /phelp nether for help