name: CrowdControl
main: com.elmakers.mine.bukkit.plugins.crowd.CrowdControlPlugin
version: 0.10
website: http://mine.elmakers.com
author: NathanWolf
description : Mainly a way to turn off ghasts in the nether.
commands:
  crowd:
    description: Control mob spawning
    usage: Use /phelp crowd for help